
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../icons/widnow_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(64, 64))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBarLayout = QtWidgets.QHBoxLayout()
        self.topBarLayout.setContentsMargins(-1, -1, 6, -1)
        self.topBarLayout.setSpacing(10)
        self.topBarLayout.setObjectName("topBarLayout")
        self.header = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.topBarLayout.addWidget(self.header)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topBarLayout.addItem(spacerItem)
        self.user_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_label.setObjectName("user_label")
        self.topBarLayout.addWidget(self.user_label)
        self.refresh_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refresh_btn.setObjectName("refresh_btn")
        self.topBarLayout.addWidget(self.refresh_btn)
        self.logout_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logout_btn.setObjectName("logout_btn")
        self.topBarLayout.addWidget(self.logout_btn)
        self.verticalLayout.addLayout(self.topBarLayout)
        self.searchBarLayout = QtWidgets.QHBoxLayout()
        self.searchBarLayout.setObjectName("searchBarLayout")
        self.search_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.search_label.setObjectName("search_label")
        self.searchBarLayout.addWidget(self.search_label)
        self.search_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_input.setObjectName("search_input")
        self.searchBarLayout.addWidget(self.search_input)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.searchBarLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.searchBarLayout)
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftPanel = QtWidgets.QWidget(parent=self.splitter)
        self.leftPanel.setObjectName("leftPanel")
        self.leftPanelLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.leftPanelLayout.setObjectName("leftPanelLayout")
        self.courseListLabel = QtWidgets.QLabel(parent=self.leftPanel)
        font = QtGui.QFont()
        font.setBold(True)
        self.courseListLabel.setFont(font)
        self.courseListLabel.setObjectName("courseListLabel")
        self.leftPanelLayout.addWidget(self.courseListLabel)
        self.course_list = QtWidgets.QListWidget(parent=self.leftPanel)
        self.course_list.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.course_list.setObjectName("course_list")
        self.leftPanelLayout.addWidget(self.course_list)
        self.selectLayout = QtWidgets.QHBoxLayout()
        self.selectLayout.setObjectName("selectLayout")
        self.leftPanelLayout.addLayout(self.selectLayout)
        self.rightPanel = QtWidgets.QWidget(parent=self.splitter)
        self.rightPanel.setObjectName("rightPanel")
        self.rightPanelLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.rightPanelLayout.setObjectName("rightPanelLayout")
        self.detailsLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setBold(True)
        self.detailsLabel.setFont(font)
        self.detailsLabel.setObjectName("detailsLabel")
        self.rightPanelLayout.addWidget(self.detailsLabel)
        self.course_details = QtWidgets.QTextBrowser(parent=self.rightPanel)
        self.course_details.setObjectName("course_details")
        self.rightPanelLayout.addWidget(self.course_details)
        self.downloadSettingsGroup = QtWidgets.QGroupBox(parent=self.rightPanel)
        self.downloadSettingsGroup.setObjectName("downloadSettingsGroup")
        self.downloadLayout = QtWidgets.QVBoxLayout(self.downloadSettingsGroup)
        self.downloadLayout.setObjectName("downloadLayout")
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.path_label = QtWidgets.QLabel(parent=self.downloadSettingsGroup)
        self.path_label.setObjectName("path_label")
        self.pathLayout.addWidget(self.path_label)
        self.path_input = QtWidgets.QLineEdit(parent=self.downloadSettingsGroup)
        self.path_input.setObjectName("path_input")
        self.pathLayout.addWidget(self.path_input)
        self.path_button = QtWidgets.QPushButton(parent=self.downloadSettingsGroup)
        self.path_button.setObjectName("path_button")
        self.pathLayout.addWidget(self.path_button)
        self.downloadLayout.addLayout(self.pathLayout)
        self.download_btn = QtWidgets.QPushButton(parent=self.downloadSettingsGroup)
        self.download_btn.setEnabled(False)
        self.download_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.download_btn.setFont(font)
        self.download_btn.setObjectName("download_btn")
        self.downloadLayout.addWidget(self.download_btn)
        self.rightPanelLayout.addWidget(self.downloadSettingsGroup)
        self.verticalLayout.addWidget(self.splitter)
        self.progressGroup = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.progressGroup.setMaximumSize(QtCore.QSize(16777215, 175))
        self.progressGroup.setObjectName("progressGroup")
        self.progressLayout = QtWidgets.QVBoxLayout(self.progressGroup)
        self.progressLayout.setObjectName("progressLayout")
        self.lecture_progress = QtWidgets.QProgressBar(parent=self.progressGroup)
        self.lecture_progress.setMinimumSize(QtCore.QSize(0, 25))
        self.lecture_progress.setProperty("value", 0)
        self.lecture_progress.setObjectName("lecture_progress")
        self.progressLayout.addWidget(self.lecture_progress)
        self.course_progress = QtWidgets.QProgressBar(parent=self.progressGroup)
        self.course_progress.setMinimumSize(QtCore.QSize(0, 25))
        self.course_progress.setProperty("value", 0)
        self.course_progress.setObjectName("course_progress")
        self.progressLayout.addWidget(self.course_progress)
        self.status_label = QtWidgets.QLabel(parent=self.progressGroup)
        font = QtGui.QFont()
        font.setBold(True)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.progressLayout.addWidget(self.status_label)
        self.current_file_label = QtWidgets.QLabel(parent=self.progressGroup)
        self.current_file_label.setText("")
        self.current_file_label.setObjectName("current_file_label")
        self.progressLayout.addWidget(self.current_file_label)
        self.stop_btn = QtWidgets.QPushButton(parent=self.progressGroup)
        self.stop_btn.setEnabled(False)
        self.stop_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.progressLayout.addWidget(self.stop_btn)
        self.verticalLayout.addWidget(self.progressGroup)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuAbout = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout_App = QtGui.QAction(parent=MainWindow)
        self.actionAbout_App.setObjectName("actionAbout_App")
        self.menuAbout.addAction(self.actionAbout_App)
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Udesel v0.1.0"))
        self.header.setText(_translate("MainWindow", "🎓 Udemy Course Manager"))
        self.user_label.setText(_translate("MainWindow", "Not logged in"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.logout_btn.setText(_translate("MainWindow", "🚪 Logout"))
        self.search_label.setText(_translate("MainWindow", "Search:"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Filter courses..."))
        self.courseListLabel.setText(_translate("MainWindow", "📚 Your Courses"))
        self.detailsLabel.setText(_translate("MainWindow", "📖 Course Details"))
        self.downloadSettingsGroup.setTitle(_translate("MainWindow", "Download Settings"))
        self.path_label.setText(_translate("MainWindow", "Save to:"))
        self.path_input.setText(_translate("MainWindow", "./downloads"))
        self.path_button.setText(_translate("MainWindow", "Browse"))
        self.download_btn.setText(_translate("MainWindow", "⬇️ Download Selected"))
        self.progressGroup.setTitle(_translate("MainWindow", "Download Progress"))
        self.lecture_progress.setFormat(_translate("MainWindow", "Lecture: %p%"))
        self.course_progress.setFormat(_translate("MainWindow", "Course: %v / %m"))
        self.status_label.setText(_translate("MainWindow", "Ready"))
        self.stop_btn.setText(_translate("MainWindow", "⏹ Stop All"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAbout_App.setText(_translate("MainWindow", "About App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
